version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      - image: circleci/node:10.13.0 # ...with this image as the primary container; this is where all `steps` will run
    # working_directory: ~/app # directory where steps will run
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: update-npm
          command: 'sudo npm install -g npm firebase-tools'
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: unit-test
          command: npm test
      - run:
          name: build
          command: npm run build
      - run:
          name: deploy-firebase
          command: firebase deploy # need as ENV: $FIREBASE_TOKEN